version: "3"

services:
  frps:
    container_name: frps
    image: snowdreamtech/frps:latest
    restart: always
    network_mode: bridge
    ports:
      - 7000:7000
    volumes:
      - ${FRPS_CONFIG_PATH:-/etc/frp}:/etc/frp
    labels:
      traefik.enable: true
      traefik.http.routers.frps.entrypoints: websecure
      traefik.http.routers.frps.rule: HostRegexp(`{subdomain:[a-zA-Z0-9-]+}.${FRPS_HOST:-frps.example.com}`)
      traefik.http.routers.frps.tls.certresolver: default
      traefik.http.routers.frps.tls.domains[0].main: ${FRPS_HOST:-frps.example.com}
      traefik.http.routers.frps.tls.domains[0].sans: "*.${FRPS_HOST:-frps.example.com}"
      traefik.http.services.frps.loadbalancer.server.port: 80
