version: "3"

services:
  postgres:
    container_name: postgres
    image: postgres:15-alpine
    restart: always
    network_mode: bridge
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
