version: "3"

services:
  subconverter:
    container_name: subconverter
    image: tindy2013/subconverter:latest
    restart: always
    network_mode: bridge
    labels:
      traefik.enable: true
      traefik.http.routers.subconverter.entrypoints: websecure
      traefik.http.routers.subconverter.rule: Host(`${HOST:-subconverter.example.com}`)
      traefik.http.routers.subconverter.tls.certresolver: zerossl
      traefik.http.services.subconverter.loadBalancer.server.port: 25500
