version: "3"

services:
  emby:
    image: emby/embyserver
    container_name: emby
    network_mode: bridge
    environment:
      - UID=1000
      - GID=1000
    volumes:
      - ${EMBY_CONFIG_PATH:-emby_config}:/config
      - ${EMBY_MEDIA_PATH:-emby_media}:/media
    ports:
      - 8096:8096
    devices:
      - /dev/dri:/dev/dri
      - /dev/vchiq:/dev/vchiq
    restart: always
