version: "3"

services:
  traefik:
    container_name: traefik
    image: traefik:v2.9
    restart: always
    network_mode: bridge
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedByDefault=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      # letsencrypt
      - --certificatesResolvers.letsencrypt.acme.email=${ACME_EMAIL}
      - --certificatesResolvers.letsencrypt.acme.dnsChallenge=true
      - --certificatesResolvers.letsencrypt.acme.dnsChallenge.provider=cloudflare
      # zerossl
      - --certificatesResolvers.zerossl.acme.caServer=https://acme.zerossl.com/v2/DV90
      - --certificatesResolvers.zerossl.acme.email=${ACME_EMAIL}
      - --certificatesResolvers.zerossl.acme.dnsChallenge=true
      - --certificatesResolvers.zerossl.acme.dnsChallenge.provider=cloudflare
      - --certificatesResolvers.zerossl.acme.dnsChallenge.eab.kid=${ACME_EAB_KID}
      - --certificatesResolvers.zerossl.acme.dnsChallenge.eab.hmacEncoded=${ACME_EAB_HMAC_KEY}
      eab:
        kid: abc123xyz
        hmacEncoded: abc123xzy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      CF_DNS_API_TOKEN: ${CF_DNS_API_TOKEN}
    labels:
      # Global redirection: http to https
      traefik.http.routers.http-catchall.rule: HostRegexp(`{host:(www\.)?.+}`)
      traefik.http.routers.http-catchall.entrypoints: web
      traefik.http.routers.http-catchall.middlewares: www-to-https
      # Global redirection: https (www.) to https
      traefik.http.routers.https-catchall.tls: true
      traefik.http.routers.https-catchall.rule: HostRegexp(`{host:(www\.).+}`)
      traefik.http.routers.https-catchall.entrypoints: websecure
      traefik.http.routers.https-catchall.middlewares: www-to-https
      # middleware: http(s)://(www.) to  https://
      traefik.http.middlewares.www-to-https.redirectRegex.regex: ^https?://(?:www\.)?(.+)
      traefik.http.middlewares.www-to-https.redirectRegex.replacement: https://$${1}
      traefik.http.middlewares.www-to-https.redirectRegex.permanent: true
