version: "3"

services:
  alist:
    container_name: alist
    image: xhofe/alist:latest
    restart: always
    network_mode: bridge
    volumes:
      - ${ALIST_DATA_PATH:-/etc/alist}:/opt/alist/data
    labels:
      traefik.enable: true
      traefik.http.routers.alist.entrypoints: websecure
      traefik.http.routers.alist.rule: Host(`${ALIST_HOST:-alist.example.com}`)
      traefik.http.routers.alist.tls.certresolver: default
