version: "3"

services:
  redis:
    container_name: redis
    image: bitnami/redis:7.0
    restart: always
    network_mode: bridge
    user: 0:0
    ports:
      - 6379:6379
    volumes:
      - /var/lib/redis:/bitnami/redis
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
